### ISSUE TITLE
How to handle nsp checks?

### ISSUE THREAD

**Issue by therealklanni** [brave/vault-updater#15]
Do we want to integrate the nsp check into a "test" step and have PRs automatically fail if nsp check fails?

**Comment by diracdeltas** [comment]
I'm in favor of that

**Comment by therealklanni** [comment]
OK, I've renamed the script to "test" (and "test-security" following convention set by @mrose17) so it will be ran in CI step. Someone just needs to enable Travis CI. :+1:
