### ISSUE TITLE
Group, count, and sort crashes by signature, allow them to be downloaded

### ISSUE THREAD

**Issue by bbondy** [brave/vault-updater#25]
Something like this but built incrementally, just being able to download and fix top crashes should be the first goal for this because it'll help our bottom line a ton.

<img width="987" alt="screenshot 2016-01-30 07 29 37" src="https://cloud.githubusercontent.com/assets/831718/12695662/59bc421c-c723-11e5-9188-c13ea4917599.png">

**Comment by aekeus** [comment]
Moved to vault-analytics
