### ISSUE TITLE
Build endpoint to receive Android daily / monthly activity pings

### ISSUE THREAD

**Issue by aekeus** [brave/vault-updater#38]
cc @SergeyZhukovsky @bbondy

**Comment by bbondy** [comment]
can we re-use the other endpoint and maybe just add a platform parameter?

**Comment by bbondy** [comment]
which when not specified defaults to laptop?

**Comment by aekeus** [comment]
I am trying to disrupt the original code as little as possible. That is why I went with a separate endpoint and mongo collection.

**Comment by bbondy** [comment]
ok managing regression risk sounds fine, thanks.
