### ISSUE TITLE
Update bitwarden

### ISSUE THREAD

**Issue by kspearrin** [brave/vault-updater#46]
Bitwarden is way out of date, using version 1.10.0 that is from early March. This version is no longer compatible with our API. Please update to the latest from the Chrome web store.

**Comment by kspearrin** [comment]
We are getting lots of support tickets from people trying to use bitwarden in brave and failing because of this. Any update? We'd rather bitwarden just be hidden and unavailable that being visible and not working at all.

/cc @bsclifton @jonathansampson

**Comment by jonathansampson** [comment]
1.14.2 appears to work well in Muon 4.3.8 and Brave 0.20.0. There are a couple issues remaining, which were covered here: https://github.com/brave/browser-laptop/issues/10202

**Comment by bsclifton** [comment]
Updated to 1.14.2.  Like @jonathansampson said, this won't fix Bitwarden- but the extension is up to date

**Comment by kspearrin** [comment]
@bsclifton Thanks. How should I go about getting future updates added? Should I open an issue here each time we release a new version? For example, we just pushed out a hotfix of our own today (v1.14.3).

**Comment by bsclifton** [comment]
@kspearrin we're still working on our support. I have some automation in place but we'll need to work out our process a little more (ex: we want to test before releasing).

Shoot me an email at `clifton@brave.com` and I'll copy some others on it. We can use email to ask for urgent updates
