### ISSUE TITLE
Update Bitwarden Extension To Latest

### ISSUE THREAD

**Issue by kspearrin** [brave/vault-updater#48]
Users often email us about missing features in these more recent versions. Please update whenever possible. Thanks.

**Comment by lukeabbott** [comment]
@kspearrin Is there anything a bitwarden + brave user like me can do to help keep Bitwarden up to date in brave?

**Comment by kspearrin** [comment]
+1 this issue I suppose? We do not control brave updates unfortunately.

**Comment by janos-szenfner** [comment]
Please Barve update the extensions. Brave does not have too much plugins/extensions. If you are handling it, please keep it up to date.

**Comment by da2x** [comment]
The current version in Brave is 1.25.5.

**Comment by da2x** [comment]
@kspearrin, magic process for future reference:

1. Download https://clients2.google.com/service/update2/crx?response=redirect&prodversion=52.0.2743.116&x=id%3Dnngceckbapebfimnlniiiahkandclblb%26uc%26lang%3Den-US&prod=chrome (that’s Bitwarden’s Chrome Store ID in there.)
2. sha256sum the resulting file
3. Update extensionManifest.json as shown in pull request #60

There could be more parts to this on Brave’s end, but I believe they rely on Chrome infrastructure? If not then such a pull request should at least spur some action.

**Comment by janos-szenfner** [comment]
Please always keep up to date it always. There are only a very few extensions in brave. Please keep those always up to date.
