### ISSUE TITLE
Use new referral download links from Fastly

### ISSUE THREAD

**Issue by aekeus** [brave/vault-updater#85]
re. https://github.com/brave/devops/issues/561

**Comment by kjozwiak** [comment]
Using macOS 10.14.2 x64 - **PASSED**

* downloaded `Brave-Browser-KRK405.pkg` using https://laptop-updates-pre.brave.com/download/KRK405 with Safari
* installed using `Brave-Browser-KRK405.pkg` and ensured that the `promoCode` file included `KRK405`
* launched Brave `0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)` and the `promoCode` was removed

Using Win 10 x64 VM - **PASSED**

* downloaded `BraveBrowserSilentSetup-KRK405.exe` using https://laptop-updates-pre.brave.com/download/KRK405 with Firefox
* installed `BraveBrowserSilentSetup-KRK405.exe` and ensured that the `promoCode` file included `KRK405`
* didn't see any UI elements when installing `0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)`, once installed, it was launched automatically
* ensured that `promoCode` was removed after `0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)` was launched

* downloaded `BraveBrowserSetup-BGF657.exe` using https://laptop-updates-pre.brave.com/download/BGF657 with Chrome
* installed `BraveBrowserSetup-BGF657.exe` and ensured that the `promoCode` file included `BGF657`
* ensured that `promoCode` was removed after `0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)` was launched

Using Win 10 x86 VM - **PASSED**

* downloaded `BraveBrowserSilentSetup32-KRK405.exe` using https://laptop-updates-pre.brave.com/download/KRK405 with Edge
* installed `BraveBrowserSilentSetup32-KRK405.exe` and ensured that the `promoCode` file included `KRK405`
* didn't see any UI elements when installing `0.58.21 Chromium: 71.0.3578.98 (Official Build) (32-bit)`, once installed, it was launched automatically
* ensured that `promoCode` was removed after `0.58.21 Chromium: 71.0.3578.98 (Official Build) (32-bit)` was launched

* downloaded `BraveBrowserSetup32-BGF657.exe` using https://laptop-updates-pre.brave.com/download/BGF657 with Firefox
* installed `BraveBrowserSetup32-BGF657.exe` and ensured that the `promoCode` file included `BGF657`
* ensured that `promoCode` was removed after `0.58.21 Chromium: 71.0.3578.98 (Official Build) (32-bit)` was launched

Using Win 8.1 x64 VM - **PASSED**

* downloaded `BraveBrowserSilentSetup-KRK405.exe` using https://laptop-updates-pre.brave.com/download/KRK405 with IE11
* installed `BraveBrowserSilentSetup-KRK405.exe` and ensured that the `promoCode` file included `KRK405`
* didn't see any UI elements when installing `0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)`, once installed, it was launched automatically
* ensured that `promoCode` was removed after `0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)` was launched

* downloaded `BraveBrowserSetup-BGF657.exe` using https://laptop-updates-pre.brave.com/download/BGF657 with Chrome
* installed `BraveBrowserSetup-BGF657.exe` and ensured that the `promoCode` file included `BGF657`
* ensured that `promoCode` was removed after `0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)` was launched

Using Win 8.1 x86 VM - **PASSED**

* downloaded `BraveBrowserSilentSetup32-KRK405.exe` using https://laptop-updates-pre.brave.com/download/KRK405 with IE11
* installed `BraveBrowserSilentSetup32-KRK405.exe` and ensured that the `promoCode` file included `KRK405`
* didn't see any UI elements when installing `0.58.21 Chromium: 71.0.3578.98 (Official Build) (32-bit)`, once installed, it was launched automatically
* ensured that `promoCode` was removed after `0.58.21 Chromium: 71.0.3578.98 (Official Build) (32-bit)` was launched

* downloaded `BraveBrowserSetup32-BGF657.exe` using https://laptop-updates-pre.brave.com/download/BGF657 with Firefox
* installed `BraveBrowserSetup32-BGF657.exe` and ensured that the `promoCode` file included `BGF657`
* ensured that `promoCode` was removed after `0.58.21 Chromium: 71.0.3578.98 (Official Build) (32-bit)` was launched

Using Win 7 x64 VM - **PASSED**

* downloaded `BraveBrowserSilentSetup-KRK405.exe` using https://laptop-updates-pre.brave.com/download/KRK405 with IE11
* installed `BraveBrowserSilentSetup-KRK405.exe` and ensured that the `promoCode` file included `KRK405`
* didn't see any UI elements when installing `0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)`, once installed, it was launched automatically
* ensured that `promoCode` was removed after `0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)` was launched

* downloaded `BraveBrowserSetup-BGF657.exe` using https://laptop-updates-pre.brave.com/download/BGF657 with Firefox
* installed `BraveBrowserSetup-BGF657.exe` and ensured that the `promoCode` file included `BGF657`
* ensured that `promoCode` was removed after `0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)` was launched

**Comment by kjozwiak** [comment]
@aekeus everything seemed to be working in terms of downloading the correct executables and parsing the referral and placing it into the `promoCode` file. I added the results above. However, the one thing that I did notice is that sometimes I'm getting `SmartScreen` errors on Win 10 for both the `silent` and `standard` installers:

<img width="1058" alt="screen shot 2019-01-15 at 1 13 27 pm" src="https://user-images.githubusercontent.com/2602313/51203930-57fd6800-18d0-11e9-891a-8062651264a9.png">

<img width="671" alt="screen shot 2019-01-15 at 1 23 52 pm" src="https://user-images.githubusercontent.com/2602313/51203934-5b90ef00-18d0-11e9-8aaa-8429abfab232.png">

I'm also noticing that I'm getting a UAC warning on Win 7 when attempting to install `silent` executables:

<img width="662" alt="screen shot 2019-01-15 at 2 15 49 pm" src="https://user-images.githubusercontent.com/2602313/51203985-84b17f80-18d0-11e9-97c3-f6a1fb1a4204.png">
