### ISSUE TITLE
exempt some referral codes from publishers anti-fraud tracking

### ISSUE THREAD

**Issue by diracdeltas** [brave/vault-updater#90]
similar to #86 but for any server-side processing of referral codes which is only needed for anti-fraud purposes. for instance IP retention for longer than 10 days is not necessary, as i understand it, for BRV001.

**Comment by aekeus** [comment]
This would require us to either hard code or store in the database configuration a list of referral codes that should not have the anti-fraud info stored in Redis.

**Comment by diracdeltas** [comment]
Can this be closed by https://github.com/brave-intl/vault-promo-services/pull/93 ?

**Comment by diracdeltas** [comment]
the exempt referral codes that i currently know of:

* BRV001
* BRA001, BRA002 (website A/B testing codes; not currently active)
* TLM305 from https://github.com/brave/internal/issues/538

**Comment by aekeus** [comment]
BRV001 is currently configured. BRA001 and BRA002 are likely misattributed to actuals -> BRT001 and BRT002.

**Comment by aekeus** [comment]
Promo services is configured with the four referral codes.

**Comment by diracdeltas** [comment]
thanks!
